### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by zorun**

### CODE REVIEW

**Comment by kerneis** [comment]
I don't understand what fb6df74 is supposed to do. Could you resubmit with a more verbose commit message please? I'm happy with the other two patches, but it's probably more sensible if I merge everything in one go. Thanks.

**Comment by zorun** [comment]
Indeed, will do.

You can see it in action at http://babelweb.polyno.me:8080/ (see the tooltip on nodes).  If you can think of a better way to visualise originated prefixes, I'm all ears.

I need to fix a small bug anyway, the prefixes are currently duplicated when we have multiple paths to a node.

**Comment by zorun** [comment]
Updated as 68349a4 (i've updated http://babelweb.polyno.me:8080/ as well).

I'm not sure about the browser compatibility of the map function, I used that to re-use existing code for 
managing sets (insertKey). If you can think of a cleaner solution, don't hesitate to fix it.

**Comment by kerneis** [comment]
array.map is fine, it's in javascript 1.6 (IE ≥ 9, Firefox ≥ 1.5): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by kerneis** [comment]
Since we are using d3, though, we should really be using Sets, but oh well…
https://github.com/mbostock/d3/wiki/Arrays#sets

**Comment by kerneis** [comment]
Rebased, updated to use d3.set() and merged. Thanks.

**Pull request closed without merging**
